### ISSUE TITLE
Getting an error while upgrading Cordova android to 7.1.1

### ISSUE THREAD

**Issue by kkbrains** [apache/cordova-plugin-inappbrowser#288]
While

 updating the Android Cordova 6.2.3 to 7.1.1 getting the following error, I am sure the issue is with the AndroidManifest.xml file but as per the [Cordova release notes ](https://cordova.apache.org/announcements/2017/12/04/cordova-android-7.0.0.html) I have pushed the changes to my config file but still getting this error.

```
: Error: ENOENT: no such file or directory, open '/Users/brains05/KK/PoolTrackr/mobile_app/platforms/android/AndroidManifest.xml'
   at Object.fs.openSync (fs.js:646:18)
   at Object.fs.readFileSync (fs.js:551:33)
   at Object.parseElementtreeSync (/Users/brains05/KK/PoolTrackr/mobile_app/platforms/android/cordova/node_modules/cordova-common/src/util/xml-helpers.js:180:27)
   at new AndroidManifest (/Users/brains05/KK/PoolTrackr/mobile_app/platforms/android/cordova/lib/AndroidManifest.js:29:20)
   at AndroidProject.getPackageName (/Users/brains05/KK/PoolTrackr/mobile_app/platforms/android/cordova/lib/AndroidProject.js:99:12)
   at Api.addPlugin (/Users/brains05/KK/PoolTrackr/mobile_app/platforms/android/cordova/Api.js:223:57)
   at handleInstall (/Users/brains05/KK/PoolTrackr/mobile_app/node_modules/cordova-lib/src/plugman/install.js:594:10)
   at /Users/brains05/KK/PoolTrackr/mobile_app/node_modules/cordova-lib/src/plugman/install.js:357:28
   at _fulfilled (/Users/brains05/KK/PoolTrackr/mobile_app/node_modules/cordova-lib/node_modules/q/q.js:787:54)
   at self.promiseDispatch.done (/Users/brains05/KK/PoolTrackr/mobile_app/node_modules/cordova-lib/node_modules/q/q.js:816:30)
(node:76349) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/Users/brains05/KK/PoolTrackr/mobile_app/platforms/android/AndroidManifest.xml'
   at Object.fs.openSync (fs.js:646:18)
   at Object.fs.readFileSync (fs.js:551:33)
   at Object.parseElementtreeSync (/Users/brains05/KK/PoolTrackr/mobile_app/platforms/android/cordova/node_modules/cordova-common/src/util/xml-helpers.js:180:27)
   at new AndroidManifest (/Users/brains05/KK/PoolTrackr/mobile_app/platforms/android/cordova/lib/AndroidManifest.js:29:20)
   at AndroidProject.getPackageName (/Users/brains05/KK/PoolTrackr/mobile_app/platforms/android/cordova/lib/AndroidProject.js:99:12)
   at Api.addPlugin (/Users/brains05/KK/PoolTrackr/mobile_app/platforms/android/cordova/Api.js:223:57)
   at handleInstall (/Users/brains05/KK/PoolTrackr/mobile_app/node_modules/cordova-lib/src/plugman/install.js:594:10)
   at /Users/brains05/KK/PoolTrackr/mobile_app/node_modules/cordova-lib/src/plugman/install.js:357:28
   at _fulfilled (/Users/brains05/KK/PoolTrackr/mobile_app/node_modules/cordova-lib/node_modules/q/q.js:787:54)
   at self.promiseDispatch.done (/Users/brains05/KK/PoolTrackr/mobile_app/node_modules/cordova-lib/node_modules/q/q.js:816:30)
(node:76349) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting apromise which was not handled with .catch(). (rejection id: 1)
(node:76349) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

Its an ionic project and here its my info

```
Ionic:

  ionic (Ionic CLI) : 4.1.1 (/usr/local/lib/node_modules/ionic)
  Ionic Framework   : ionic1 1.3.0
  @ionic/v1-toolkit : 1.0.0

Cordova:

  cordova (Cordova CLI) : 8.0.0
  Cordova Platforms     : none
  Cordova Plugins       : no whitelisted plugins (27 plugins total)

System:

  Android SDK Tools : 26.0.2 (/usr/local/opt/android-sdk)
  ios-deploy        : 2.0.0
  NodeJS            : v8.11.3 (/usr/local/bin/node)
  npm               : 6.4.0
  OS                : macOS High Sierra
  Xcode             : Xcode 9.4.1 Build version 9F2000
```

**Comment by janpio** [comment]
What is the connection to `cordova-plugin-inappbrowser` here?
Have you updated all your plugins? What does `cordova plugin list` return? And `npm outdated`?

**Comment by jcesarmobile** [comment]
this was a cordova-android bug and was fixed long ago
