### ISSUE TITLE
[Tests/CI/Travis] android-7.0 tests are failing

### ISSUE THREAD

**Issue by janpio** [apache/cordova-plugin-inappbrowser#307]
This is the configration that is failing:

```
  "os": "linux",
  "env": "PLATFORM=android-7.0",
  "jdk": "oraclejdk8",
```

Last successful build was:
https://travis-ci.org/apache/cordova-plugin-inappbrowser/builds/344652192
(Feb 22)

First failing build was:
https://travis-ci.org/apache/cordova-plugin-inappbrowser/builds/357149499
(Mar 21)

(end of page #1 of https://github.com/apache/cordova-plugin-inappbrowser/commits/master right now)

Error message on Travis was:

```
...
..............................................
cordova-paramedic: connecting to app
cordova-paramedic: waiting for test results
cordova-paramedic: Tests failed to complete; ending appium session. The error is:
Error: Seems like device not connected to local server in 300 secs
    at null._onTimeout (/tmp/paramedic/lib/paramedic.js:467:24)
    at Timer.listOnTimeout (timers.js:92:15)
Running Appium tests on Sauce Labs
Couldn't find Appium tests, skipping...
Completed tests at 10:02:21 AM
Getting saucelabs jobs details...
============================================================================================
Job name: travis-plugin-inappbrowser-436.10
Job ID: 11b69418b01a4cc1b09607b000b9e40c
Job URL: https://saucelabs.com/beta/tests/11b69418b01a4cc1b09607b000b9e40c
...
```

Commit was: https://github.com/apache/cordova-plugin-inappbrowser/commit/65a825a1934ef93d886225c9c56f98fcec50ef38 So nothing concerning Android, so probably more a testing environment thing.

Most commits after that one were failing with the same test failing. 
Some succeeded without a real reason.
Some other more recent commits succeeded because the test was just removed.

--- 

More recent test run that is failing, where the video and logs are still available on Saucelabs:

```
cordova-paramedic: connecting webdriver
...........................
cordova-paramedic: connecting to app
cordova-paramedic: waiting for test results
cordova-paramedic: Tests failed to complete; ending appium session. The error is:
Error: waitForTests: Seems like device not connected to local server in 540 secs
    at null._onTimeout (/tmp/paramedic/lib/paramedic.js:467:24)
    at Timer.listOnTimeout (timers.js:92:15)
Running Appium tests on Sauce Labs
Couldn't find Appium tests, skipping...
Completed tests at 1:25:20 PM
Getting saucelabs jobs details...
============================================================================================
Job name: travis-plugin-inappbrowser-516.10
Job ID: 8a2a6c5d12714125b366852914355361
Job URL: https://saucelabs.com/beta/tests/8a2a6c5d12714125b366852914355361
Video: https://assets.saucelabs.com/jobs/8a2a6c5d12714125b366852914355361/video.flv
Appium logs: https://assets.saucelabs.com/jobs/8a2a6c5d12714125b366852914355361/selenium-server.log
Logcat logs: https://saucelabs.com/jobs/8a2a6c5d12714125b366852914355361/logcat.log
============================================================================================
```

The screenshot indicates that the tests run and and finish just fine.

**Comment by janpio** [comment]
Compare the failing test here, to a similarly configured one from another plugin:

failing here:
https://travis-ci.org/apache/cordova-plugin-inappbrowser/jobs/435601803
https://saucelabs.com/beta/tests/7e834da3d10d4f08b614d05fcccdfa39/metadata#6

succeeding over there:
https://travis-ci.org/apache/cordova-plugin-geolocation/jobs/435617323
https://saucelabs.com/beta/tests/86c40977eac144848f0342e4b7cfb048/metadata#11

**Comment by janpio** [comment]
Last 2 entries from "Appium Logs":

```
  ...
  {
    "screenshot": null,
    "between_commands": 0.21913504600524902,
    "suggestion_values": [],
    "request": {
      "using": "xpath",
      "value": "//android.widget.Button[translate(@text, \"alow\", \"ALOW\")=\"ALLOW\"]"
    },
    "HTTPStatus": 500,
    "result": "ERROR user closed connection while waiting for command to complete",
    "suggestion": null,
    "duration": 299.9810121059418,
    "path": "element",
    "method": "POST",
    "timelineSeconds": 20.475893020629883
  },
  {
    "screenshot": 1,
    "between_commands": 237.02974104881287,
    "suggestion_values": [],
    "request": null,
    "HTTPStatus": 200,
    "result": "",
    "suggestion": null,
    "duration": 0.00030684471130371094,
    "path": "/session/7e834da3d10d4f08b614d05fcccdfa39",
    "method": "DELETE",
    "statusCode": 0,
    "timelineSeconds": 320.6760401725769
  }
]
```

I don't really understand what `"//android.widget.Button[translate(@text, \"alow\", \"ALOW\")=\"ALLOW\"]"` does and where it comes from.

Update: Got it: https://github.com/apache/cordova-paramedic/blob/31155dfd9287e9c53b034bc00dba4473f7c9bf5c/lib/appium/helpers/wdHelper.js#L282

**Comment by janpio** [comment]
Turn out the successful test run in `cordova-plugin-geolocation` has the same line with `alow` in it in line 146 the Appium logs - and all the lines before it are identical to our failing test run.

There it results in this:

```
  {
    "screenshot": null,
    "between_commands": 0.19422101974487305,
    "suggestion_values": [],
    "request": {
      "using": "xpath",
      "value": "//android.widget.Button[translate(@text, \"alow\", \"ALOW\")=\"ALLOW\"]"
    },
    "HTTPStatus": 200,
    "result": {
      "ELEMENT": "1"
    },
    "suggestion": null,
    "duration": 0.032217979431152344,
    "path": "element",
    "method": "POST",
    "statusCode": 0,
    "timelineSeconds": 18.396260023117065
  },
```

And then the actual testing starts:

```
{
    "screenshot": 1,
    "between_commands": 0.6282658576965332,
    "suggestion_values": [],
    "request": {},
    "HTTPStatus": 200,
    "result": true,
    "suggestion": null,
    "duration": 3.1124610900878906,
    "path": "element/1/click",
    "method": "POST",
    "statusCode": 0,
    "timelineSeconds": 18.62269902229309
  },
  {
    "screenshot": null,
    "between_commands": 0.5536580085754395,
    "suggestion_values": [],
    "request": {
      "name": "WEBVIEW_io.cordova.hellocordova"
    },
    "HTTPStatus": 200,
    "result": null,
    "suggestion": null,
    "duration": 0.10723495483398438,
    "path": "context",
    "method": "POST",
    "statusCode": 0,
    "timelineSeconds": 22.363425970077515
  },
...
```

So: Why is this failing for inappbrowser?

**Comment by janpio** [comment]
Similar situation in the Appium Server log as before in the normal Appium log: First 281 lines are identical, then our failing run is just this:

```
2018-10-01 13:31:30:186 - [HTTP] <-- POST /wd/hub/session/2e31ca5a-b13c-4abe-af4b-5e94c0b560c1/element - - ms - - 
2018-10-01 13:31:30:326 - [HTTP] --> POST /wd/hub/session/2e31ca5a-b13c-4abe-af4b-5e94c0b560c1/context {"name":"WEBVIEW_io.cordova.hellocordova"}
2018-10-01 13:31:30:327 - [debug] [MJSONWP] Calling AppiumDriver.setContext() with args: ["WEBVIEW_io.cordova.hellocordova","2e31ca5a-b13c-4abe-af4b-5e94c0b560c1"]
```

while the succeeding one continues:

```2018-10-01 13:52:46:540 - [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[CLASS=android.widget.Button, INSTANCE=1]
2018-10-01 13:52:46:542 - [debug] [AndroidBootstrap] Received command result from bootstrap
2018-10-01 13:52:46:544 - [debug] [MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"1"}
2018-10-01 13:52:46:544 - [HTTP] <-- POST /wd/hub/session/36a4d6ba-50d0-4135-8adb-5bd90b912d45/element 200 29 ms - 87 
2018-10-01 13:52:46:545 - [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":{"ELEMENT":"1"}}
2018-10-01 13:52:47:176 - [HTTP] --> POST /wd/hub/session/36a4d6ba-50d0-4135-8adb-5bd90b912d45/element/1/click {}
2018-10-01 13:52:47:176 - [debug] [MJSONWP] Calling AppiumDriver.click() with args: ["1","36a4d6ba-50d0-4135-8adb-5bd90b912d45"]
2018-10-01 13:52:47:177 - [debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"element:click","params":{"elementId":"1"}}
2018-10-01 13:52:47:178 - [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"element:click","params":{"elementId":"1"}}
2018-10-01 13:52:47:181 - [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
2018-10-01 13:52:47:181 - [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: click
2018-10-01 13:52:50:282 - [debug] [AndroidBootstrap] Received command result from bootstrap
2018-10-01 13:52:50:284 - [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":true}
2018-10-01 13:52:50:284 - [debug] [MJSONWP] Responding to client with driver.click() result: true
2018-10-01 13:52:50:285 - [HTTP] <-- POST /wd/hub/session/36a4d6ba-50d0-4135-8adb-5bd90b912d45/element/1/click 200 3109 ms - 76 
2018-10-01 13:52:50:841 - [HTTP] --> POST /wd/hub/session/36a4d6ba-50d0-4135-8adb-5bd90b912d45/context {"name":"WEBVIEW_io.cordova.hellocordova"}
2018-10-01 13:52:50:842 - [debug] [MJSONWP] Calling AppiumDriver.setContext() with args: ["WEBVIEW_io.cordova.hellocordova","36a4d6ba-50d0-4135-8adb-5bd90b912d45"]
2018-10-01 13:52:50:842 - [debug] [AndroidDriver] Getting a list of available webviews
2018-10-01 13:52:50:843 - [debug] [ADB] Getting connected devices...
2018-10-01 13:52:50:852 - [debug] [ADB] 1 device(s) connected
2018-10-01 13:52:50:852 - [debug] [ADB] Running '/home/chef/android-sdk-linux/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","cat","/proc/net/unix"]
2018-10-01 13:52:50:863 - [debug] [AndroidDriver] WEBVIEW_3775 mapped to pid 3775
2018-10-01 13:52:50:864 - [debug] [AndroidDriver] Getting process name for webview
2018-10-01 13:52:50:864 - [debug] [ADB] Getting connected devices...
2018-10-01 13:52:50:870 - [debug] [ADB] 1 device(s) connected
2018-10-01 13:52:50:870 - [debug] [ADB] Running '/home/chef/android-sdk-linux/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","ps"]
2018-10-01 13:52:50:887 - [debug] [AndroidDriver] Parsed pid: 3775 pkg: io.cordova.hellocordova!
2018-10-01 13:52:50:887 - [debug] [AndroidDriver] from: u0_a72,3775,1361,2355300,113052,ep_poll,0000000000,S,io.cordova.hellocordova
2018-10-01 13:52:50:889 - [debug] [AndroidDriver] returning process name: io.cordova.hellocordova
2018-10-01 13:52:50:889 - [debug] [AndroidDriver] Found webviews: ["WEBVIEW_io.cordova.hellocordova"]
2018-10-01 13:52:50:890 - [debug] [AndroidDriver] Available contexts: ["NATIVE_APP","WEBVIEW_io.cordova.hellocordova"]
2018-10-01 13:52:50:890 - [debug] [AndroidDriver] Connecting to chrome-backed webview context 'WEBVIEW_io.cordova.hellocordova'
...
```

**Comment by janpio** [comment]
### Preliminary result

This code here hangs:
https://github.com/apache/cordova-paramedic/blob/5bed039d6dfbb758a19e066d27a2aa1c1739b2f5/lib/appium/helpers/wdHelper.js#L281-L284
Either it doesn't find the button or is blocked somehow else.
Then after the timeout is over, the tests return and fail.

(I don't understand why the final screenshot for the failing test after the timeout shows successful Jasmin test run though - makes no sense to me.)

**Comment by janpio** [comment]
(Maybe the test is actually already run - and Appium is trying to take care of other stuff)

In the successful run for `geolocation`, I noticed that after clicking that button it does somethign with `window_handles`. Turns out, that is actually some code specifically there for inappbrowser:

https://github.com/apache/cordova-paramedic/blob/5bed039d6dfbb758a19e066d27a2aa1c1739b2f5/lib/appium/helpers/wdHelper.js#L217-L227

(But as this code is not even run in the failing tests, this of course can not be the reason for the failure.)

**Comment by janpio** [comment]
Watching the video of the test run at https://saucelabs.com/beta/tests/7e834da3d10d4f08b614d05fcccdfa39/watch#5 confirm that the tests are actually run during the first 35seconds of the video, then just nothing happens any more for the rest of the video.

Test successful test run for geolocation also executes the tests right from the beginning, but then gets an actual permission prompt that can be allowed:
![image](https://user-images.githubusercontent.com/183673/46296422-a0e81580-c59a-11e8-881b-41effb821882.png)
https://saucelabs.com/beta/tests/86c40977eac144848f0342e4b7cfb048/watch#7
This happens, and then the test finishes after ~40 seconds.

**Comment by janpio** [comment]
So probably better comparison is `cordova-plugin-dialogs`:
https://travis-ci.org/apache/cordova-plugin-dialogs/jobs/435622691
https://saucelabs.com/beta/tests/1473fce577824bf89398aae88369dc1c/watch#10
Tests run, then a few seconds nothing and then the test finishes. No permission prompt.

**Comment by janpio** [comment]
Observation on the Saucelabs "Commands" tab:

No red border for "POST element" line:
![image](https://user-images.githubusercontent.com/183673/46296733-55823700-c59b-11e8-924a-743ebd9236b6.png)

Then a red border for our failing inappbrowser:
![image](https://user-images.githubusercontent.com/183673/46296762-65018000-c59b-11e8-859b-7f29cb334fcd.png)

But also a red border for the dialogs plugin:
![image](https://user-images.githubusercontent.com/183673/46296781-72b70580-c59b-11e8-8222-ad628498db2a.png)

So this probably just means that it couldn'T find the element (remember: This is looking for an "Allow" button to click). Which is also why `dialogs` doesn't have the ` POST element/1/click ` line that geolocation does.

Remains the question: Why does nothing happen here on inAppBrowser?

These are the steps that should follow but never do:
![image](https://user-images.githubusercontent.com/183673/46296930-c4f82680-c59b-11e8-9d11-e7ae91e2dc81.png)

**Comment by janpio** [comment]
Noticed one more thing in our failing test run on Saucelabs:
![image](https://user-images.githubusercontent.com/183673/46296984-e78a3f80-c59b-11e8-811e-164f933c3fcc.png)

For the successful dialogs plugin this is just:
![image](https://user-images.githubusercontent.com/183673/46297003-f670f200-c59b-11e8-9b57-d66a7859e870.png)

**Comment by alsorokin** [comment]
It might be some trouble with context switching on Appium. We've already had something similar, and with InAppBrowser again, and I vaguely remember having to code some workaround in Paramedic for that.

**Comment by alsorokin** [comment]
The command looking for "Allow" button should fail shortly, as it does in `dialogs`, but for some reason it times out after a minute.

**Comment by janpio** [comment]
> We've already had something similar, and with InAppBrowser again, and I vaguely remember having to code some workaround in Paramedic for that.

Yeah, I linked to that above:
https://github.com/apache/cordova-plugin-inappbrowser/issues/307#issuecomment-425932393

**Comment by janpio** [comment]
Found the actual workaround you probably meant - we did not bust the permissions for the splashscreen plugin because it was hanging on Android 7. Expanded that to inappbrowser, and voila, it works 🥇
