### ISSUE TITLE
cordova-android@7.0.0  Failed to install 'cordova-plugin-inappbrowser'  

### ISSUE THREAD

**Issue by happyi** [apache/cordova-plugin-inappbrowser#400]
Failed to install 'cordova-plugin-inappbrowser': Error: ENOENT: no such file or directory, open '/Users/yutingting/workspace/yiren-test/platforms/android/AndroidManifest.xml'
    at Object.fs.openSync (fs.js:545:3)
    at Object.fs.readFileSync (fs.js:451:33)
    at Object.parseElementtreeSync (/Users/yutingting/workspace/yiren-test/platforms/android/cordova/node_modules/cordova-common/src/util/xml-helpers.js:180:27)
    at new AndroidManifest (/Users/yutingting/workspace/yiren-test/platforms/android/cordova/lib/AndroidManifest.js:29:20)
    at AndroidProject.getPackageName (/Users/yutingting/workspace/yiren-test/platforms/android/cordova/lib/AndroidProject.js:99:12)
    at Api.addPlugin (/Users/yutingting/workspace/yiren-test/platforms/android/cordova/Api.js:223:57)
    at handleInstall (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:594:10)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:357:28
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:787:54)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:816:30

**Comment by janpio** [comment]
Don't use an old version of cordova-android, use the most recent one.
Same for the plugin, if you are not installing the most recent version (which we can't know as you didn't include the version here).

**Comment by happyi** [comment]
thank's upgrade cordova  it's works
