### ISSUE TITLE
window.open crashed mobile app when upgrade targetSdkVersion from 23 to 26

### ISSUE THREAD

**Issue by pbriso** [apache/cordova-plugin-inappbrowser#415]
Hello, 

I hope someone can help me with this problem, which is possibly easy to solve but I do not give with it.

I have a cordova project and I use cordova-plugin-inappbrowser in version 1.5.0. The plugin has always worked well until I modified the androidmanifest.xml targetSdkVersion from

`<uses-sdk android: minSdkVersion = "16" android: targetSdkVersion = "23" />`
to
`<uses-sdk android: minSdkVersion = "16" android: targetSdkVersion = "26" />`

I use Cordova CLI 6.5.0

When I compile the app with this change, the application crashed when I use
`var ref = cordova.InAppBrowser.open (filePath, '_system', 'location = no');
`
for any type of file.

Please help me. Thank you

**Comment by nijesh17** [comment]
I'm also facing the same issue, can any one help

**Comment by timbru31** [comment]
Could you provide a crash log (e.g. from logcat?). This helps us to debug

**Comment by AthiraWD** [comment]
@timbru31 Here is the error log

`2019-04-25 10:01:09.555 4630-4630/com.bmb.wiredelta E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.bmb.wiredelta, PID: 4630
    java.lang.NumberFormatException: For input string: "141414;"
        at java.lang.Long.parseLong(Long.java:594)
        at android.graphics.Color.parseColor(Color.java:1386)
        at org.apache.cordova.inappbrowser.InAppBrowser$6.createCloseButton(InAppBrowser.java:660)
        at org.apache.cordova.inappbrowser.InAppBrowser$6.run(InAppBrowser.java:811)
        at android.app.Activity.runOnUiThread(Activity.java:6282)
        at org.apache.cordova.inappbrowser.InAppBrowser.showWebPage(InAppBrowser.java:970)
        at org.apache.cordova.inappbrowser.InAppBrowser$1.run(InAppBrowser.java:232)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
    
    
    --------- beginning of system
2019-04-25 10:01:09.571 1592-1592/? E/lowmemorykiller: Error writing /proc/4630/oom_score_adj; errno=22`

**Comment by nijesh17** [comment]
@timbru31 Here is the error log
`2019-04-25 10:01:09.555 4630-4630/com.bmb.wiredelta E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.bmb.wiredelta, PID: 4630
    java.lang.NumberFormatException: For input string: "141414;"
        at java.lang.Long.parseLong(Long.java:594)
        at android.graphics.Color.parseColor(Color.java:1386)
        at org.apache.cordova.inappbrowser.InAppBrowser$6.createCloseButton(InAppBrowser.java:660)
        at org.apache.cordova.inappbrowser.InAppBrowser$6.run(InAppBrowser.java:811)
        at android.app.Activity.runOnUiThread(Activity.java:6282)
        at org.apache.cordova.inappbrowser.InAppBrowser.showWebPage(InAppBrowser.java:970)
        at org.apache.cordova.inappbrowser.InAppBrowser$1.run(InAppBrowser.java:232)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
    
    
    --------- beginning of system
2019-04-25 10:01:09.571 1592-1592/? E/lowmemorykiller: Error writing /proc/4630/oom_score_adj; errno=22`

**Comment by nijesh17** [comment]
I fixed the issue.
Issue is extra semicolon in closebuttoncolor property

`options : InAppBrowserOptions = {
........,
closebuttoncolor: '#141414;',
........ ,
}`
to
`options : InAppBrowserOptions = {
........,
closebuttoncolor: '#141414',
........ ,
}`

**Comment by BigBerny** [comment]
Also "#fff" will result in a crash. So make sure you use "#ffffff" (6 characters)!
