### ISSUE TITLE
Tests are failing on iOS 12.2

### ISSUE THREAD

**Issue by janpio** [apache/cordova-plugin-inappbrowser#491]
https://travis-ci.org/apache/cordova-plugin-inappbrowser/jobs/547251173

```
cordova-paramedic: Tests failed to complete; ending appium session. The error is:
Error: [context("WEBVIEW_5181.2")] Error response status: 13, UnknownError - An unknown server-side error occurred while processing the command. Selenium error: An unknown server-side error occurred while processing the command. Original error: Remote debugger error with code '-32601': 'Page' domain was not found
    at exports.newError (/Users/travis/.nvm/versions/node/v6.17.1/lib/node_modules/cordova-paramedic/node_modules/wd/lib/utils.js:152:13)
    at /Users/travis/.nvm/versions/node/v6.17.1/lib/node_modules/cordova-paramedic/node_modules/wd/lib/callbacks.js:36:19
    at /Users/travis/.nvm/versions/node/v6.17.1/lib/node_modules/cordova-paramedic/node_modules/wd/lib/webdriver.js:194:5
    at Request._callback (/Users/travis/.nvm/versions/node/v6.17.1/lib/node_modules/cordova-paramedic/node_modules/wd/lib/http-utils.js:89:7)
    at Request.self.callback (/Users/travis/.nvm/versions/node/v6.17.1/lib/node_modules/cordova-paramedic/node_modules/request/request.js:185:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/travis/.nvm/versions/node/v6.17.1/lib/node_modules/cordova-paramedic/node_modules/request/request.js:1161:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
From previous event:
    at ParamedicSauceLabs.runSauceTests (/Users/travis/.nvm/versions/node/v6.17.1/lib/node_modules/cordova-paramedic/lib/ParamedicSauceLabs.js:459:14)
    at ParamedicRunner.runTests (/Users/travis/.nvm/versions/node/v6.17.1/lib/node_modules/cordova-paramedic/lib/paramedic.js:337:58)
    at Q.then.then.then (/Users/travis/.nvm/versions/node/v6.17.1/lib/node_modules/cordova-paramedic/lib/paramedic.js:89:29)
```

https://app.saucelabs.com/tests/b3c7f179af914ced899a8daa222da1d0 shows this happening quite early:

![image](https://user-images.githubusercontent.com/183673/59803057-ad5bfc00-92ea-11e9-9d32-b7c723eda0c4.png)

**Comment by janpio** [comment]
Compare that to successful test run on iOS 12.0:

https://travis-ci.org/apache/cordova-plugin-inappbrowser/jobs/547251172
https://app.saucelabs.com/tests/41ce94fb36fd482b84dcbaae976e096d
![image](https://user-images.githubusercontent.com/183673/59803131-e3997b80-92ea-11e9-8b0f-c270bfaed97a.png)

Note that "GET context" here only returns 2 objects (1 native_app, 1 webview) - the failing one returns 2 webviews.

**Comment by janpio** [comment]
The return of multiple webviews here should be covered by the code:
https://github.com/apache/cordova-paramedic/blob/01ed7897bd02bb365597ef46920f37a93db1e903/lib/appium/helpers/wdHelper.js#L121-L124
Unfortunately this code does not work as commented, but takes the _first_ webview.

Try to fix via: https://github.com/apache/cordova-paramedic/commit/182124374a12b34b206c34511a942ab020d49a7e

**Comment by janpio** [comment]
Didn't help.

**Comment by janpio** [comment]
Next try: https://github.com/apache/cordova-paramedic/commit/16877acc101f959f9c3579bc4b67968bf276a82c
(via https://github.com/appium/appium/issues/12518)

**Comment by janpio** [comment]
One step further, but another failure:
https://travis-ci.org/apache/cordova-plugin-inappbrowser/jobs/547251173
https://app.saucelabs.com/tests/edde164244ce44c497e21c1ff95b5126

**Comment by janpio** [comment]
Different failure this time:

https://travis-ci.org/apache/cordova-plugin-inappbrowser/jobs/547251173
https://app.saucelabs.com/tests/f9f886302e8d458395185759a40dde8b

![image](https://user-images.githubusercontent.com/183673/59836182-5a666100-934b-11e9-8260-beab56b1defd.png)
![image](https://user-images.githubusercontent.com/183673/59836205-67835000-934b-11e9-808a-b92881224012.png)

(not really sure why `appium `is mentioned there, as this should be the normal test run)

Note that the tests themselves seem to pass just fine, it's just sending these results that fails somehow.
