### ISSUE TITLE
.open does not support windowFeatures with no `=` in them

### ISSUE THREAD

**Issue by AdriVanHoudt** [apache/cordova-plugin-inappbrowser#795]
# Bug Report

### What is expected to happen?

`iab.open('https://example.com', '_system', 'noopener')`
opens the webpage

### What does actually happen?

It throws
```java
E/PluginManager: Uncaught exception from plugin
    java.util.NoSuchElementException
        at java.util.StringTokenizer.nextToken(StringTokenizer.java:349)
        at org.apache.cordova.inappbrowser.InAppBrowser.parseFeature(InAppBrowser.java:447)
        at org.apache.cordova.inappbrowser.InAppBrowser.execute(InAppBrowser.java:174)
        at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:117)
        at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
        at org.apache.cordova.PluginManager.exec(PluginManager.java:132)
        at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
        at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:336)
        at android.os.Looper.loop(Looper.java:174)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

## Information

I believe it is https://github.com/apache/cordova-plugin-inappbrowser/blob/46c080f59a011747ba1b70f462b27fee26957247/src/android/InAppBrowser.java#L436-L456
that expects there to always be an `=` with a value for every windowFeature.
`iab.open('https://example.com', '_system', 'noopener=')` also doesn't work.

I can try to put a PR together that doesn't try and parse out the value when not there but no idea what the implication is.
It does seem like showWebPage just ignores noopener and noreferrer outright https://github.com/apache/cordova-plugin-inappbrowser/blob/46c080f59a011747ba1b70f462b27fee26957247/src/android/InAppBrowser.java#L637

### Environment, Platform, Device

Android

### Version information

Plugin version 4.0.0
Cordova android 9.0.0

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by AdriVanHoudt** [comment]
It appears that on iOS it is also not supported but the code just ignores anything without a value. Causing to still work while on android it throws causing the open not to happen.

https://github.com/apache/cordova-plugin-inappbrowser/blob/46c080f59a011747ba1b70f462b27fee26957247/src/ios/CDVInAppBrowserOptions.m#L64

**Comment by graysoncroom** [comment]
Has anyone found a workaround for this issue?

**Comment by AdriVanHoudt** [comment]
This is what we kinda do atm
```js
// We want the inAppBrowser to handle our opens on mobile
// This is needed to make tel: links work on iOS for example
// This was removed from the plugin itself in https://github.com/apache/cordova-plugin-inappbrowser/pull/600
$window.open = function open(url, target, windowFeatures) {

    // noopener and noreferrer are not supported by the inAppBrowser
    // It even crashes on Android https://github.com/apache/cordova-plugin-inappbrowser/issues/795
    if (windowFeatures) {
        windowFeatures = windowFeatures.replace(/noopener|noreferrer/g, '');
    }

     return cordova.InAppBrowser.open(url, target, windowFeatures);
};
```
