### ISSUE TITLE
Invalid package.json when trying to download manually plugin

### ISSUE THREAD

**Issue by krem06** [apache/cordova-plugin-inappbrowser#938]
I am trying to modify plugin as I am having problems with intent urls. To do so I downloaded the repo:
git clone git@github.com:apache/cordova-plugin-inappbrowser.git

Then I executed my local version of plugin using:
cordova plugin add --link custom/cordova-plugin-inappbrowser --save

That's when I get an 'Invalid package.json' error:

npm-session aa9aea1d369aba26
Error: Invalid package.json
    at /.nvm/versions/node/v13.13.0/lib/node_modules/npm/lib/view.js:104:30
    at tryCatcher (/.nvm/versions/node/v13.13.0/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.errorAdapter [as _rejectionHandler0] (/.nvm/versions/node/v13.13.0/lib/node_modules/npm/node_modules/bluebird/js/release/nodeify.js:35:34)
    at Promise._settlePromise (/.nvm/versions/node/v13.13.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:571:21)
    at Promise._settlePromise0 (/.nvm/versions/node/v13.13.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/.nvm/versions/node/v13.13.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:695:18)
    at _drainQueueStep (/.nvm/versions/node/v13.13.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/.nvm/versions/node/v13.13.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/.nvm/versions/node/v13.13.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/.nvm/versions/node/v13.13.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (internal/timers.js:456:21)
Darwin 20.4.0
argv "/.nvm/versions/node/v13.13.0/bin/node" "/.nvm/versions/node/v13.13.0/bin/npm" "view" "custom/cordova-plugin-inappbrowser" "--json"
node v13.13.0
npm  v6.14.4
error Invalid package.json
exit [ 1, true ]

---

I tried to execute 'plugman createpackagejson PATH_TO_PLUGIN' but didn't work either...

What could cause this problem? Was my procedure to download and use plugin correct? TY

**Comment by krem06** [comment]
I just forked repo downloaded it, modified and reupload on my local git repo. 

Then following command worked properly:
git clone git@github.com:krem06/cordova-plugin-inappbrowser.git custom/cordova-plugin-inappbrowser
cordova plugin add --link custom/cordova-plugin-inappbrowser
