### ISSUE TITLE
Crash app when click

### ISSUE THREAD

**Issue by oleksandrdevqube** [apache/cordova-plugin-inappbrowser#954]
# Bug Report

### What is expected to happen?
When I go to innappbrowser and click on select, or if I open YouTube then the application closes.
(Only Android)

## Information
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: , PID: 25942
    android.content.res.Resources$NotFoundException: Resource ID #0x0
        at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:225)
        at android.content.res.Resources.loadXmlResourceParser(Resources.java:2446)
        at android.content.res.Resources.getLayout(Resources.java:1252)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:536)
        at android.widget.ArrayAdapter.createViewFromResource(ArrayAdapter.java:425)
        at android.widget.ArrayAdapter.getView(ArrayAdapter.java:416)
        at ml0.getView(chromium-TrichromeWebViewGoogle6432.aab-stable-506005334:53)
        at android.widget.AbsListView.obtainView(AbsListView.java:2398)
        at android.widget.ListView.measureHeightOfChildren(ListView.java:1417)
        at android.widget.ListView.onMeasure(ListView.java:1323)
        at android.view.View.measure(View.java:25833)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6980)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:25833)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6980)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:25833)
        at com.android.internal.widget.AlertDialogLayout.tryOnMeasure(AlertDialogLayout.java:146)
        at com.android.internal.widget.AlertDialogLayout.onMeasure(AlertDialogLayout.java:71)
        at android.view.View.measure(View.java:25833)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6980)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:25833)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6980)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:25833)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6980)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:758)
        at android.view.View.measure(View.java:25833)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3682)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2433)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2739)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2179)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8793)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1037)
        at android.view.Choreographer.doCallbacks(Choreographer.java:845)
        at android.view.Choreographer.doFrame(Choreographer.java:780)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7870)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

### Version information
ext {
    minSdkVersion = 24
    compileSdkVersion = 32
    targetSdkVersion = 30
    androidxActivityVersion = '1.2.0'
    androidxAppCompatVersion = '1.2.0'
    androidxCoordinatorLayoutVersion = '1.1.0'
    androidxCoreVersion = '1.3.2'
    androidxFragmentVersion = '1.3.0'
    junitVersion = '4.13.1'
    androidxJunitVersion = '1.1.2'
    androidxEspressoCoreVersion = '3.3.0'
    cordovaAndroidVersion = '7.0.0'
}

dependencies": {
    "@angular/common": "~12.0.1",
    "@angular/core": "~12.0.1",
    "@angular/forms": "~12.0.1",
    "@angular/google-maps": "^12.1.1",
    "@angular/platform-browser": "~12.0.1",
    "@angular/platform-browser-dynamic": "~12.0.1",
    "@angular/router": "~12.0.1",
    "@capacitor-community/http": "^1.2.0",
    "@capacitor/android": "3.0.2",
    "@capacitor/app": "1.0.1",
    "@capacitor/core": "3.0.1",
    "@capacitor/device": "^1.0.2",
    "@capacitor/geolocation": "^1.0.1",
    "@capacitor/haptics": "1.0.1",
    "@capacitor/ios": "3.0.2",
    "@capacitor/keyboard": "1.0.1",
    "@capacitor/push-notifications": "^1.0.3",
    "@capacitor/splash-screen": "^1.0.2",
    "@capacitor/status-bar": "1.0.1",
    "@capacitor/storage": "^1.0.2",
    "@ionic-native/app-version": "^5.34.0",
    "@ionic-native/camera": "^5.35.0",
    "@ionic-native/core": "^5.33.1",
    "@ionic-native/device": "^5.35.0",
    "@ionic-native/diagnostic": "^5.36.0",
    "@ionic-native/file": "^5.34.0",
    "@ionic-native/file-transfer": "^5.35.0",
    "@ionic-native/firebase-crashlytics": "^5.34.0",
    "@ionic-native/health": "^5.34.0",
    "@ionic-native/in-app-browser": "^5.33.1",
    "@ionic-native/in-app-purchase-2": "^5.33.1",
    "@ionic-native/native-geocoder": "^5.33.1",
    "@ionic-native/photo-library": "^5.35.0",
    "@ionic-native/screen-orientation": "^5.35.0",
    "@ionic/angular": "^5.5.2",
    "@ngrx/effects": "^12.1.0",
    "@ngrx/store": "^12.1.0",
    "@ngx-translate/core": "^13.0.0",
    "@ngx-translate/http-loader": "^6.0.0",
    "chart.js": "^2.9.3",
    "chartjs-plugin-annotation": "0.5.7",
    "cordova-plugin-app-version": "^0.1.12",
    "cordova-plugin-camera": "^5.0.2",
    "cordova-plugin-device": "^2.0.3",
    "cordova-plugin-file": "^6.0.2",
    "cordova-plugin-file-transfer": "^1.7.1",
    "cordova-plugin-firebase-crashlytics": "^1.2.0",
    "cordova-plugin-geolocation": "^4.1.0",
    "cordova-plugin-health": "^2.0.2",
    "cordova-plugin-inappbrowser": "^5.0.0",
    "cordova-plugin-nativegeocoder": "^3.4.1",
    "cordova-plugin-photo-library": "^2.3.1",
    "cordova-plugin-purchase": "^10.6.0",
    "cordova-plugin-screen-orientation": "^3.0.2",
    "cordova-plugin-whitelist": "^1.3.5",
    "cordova.plugins.diagnostic": "^6.0.3",
    "date-fns": "^2.22.1",
    "jetifier": "^2.0.0",
    "ng2-charts": "^2.3.0",
    "ngx-pipes": "^2.7.5",
    "rxjs": "~6.6.0",
    "swiper": "^7.4.1",
    "tslib": "^2.0.0",
    "zone.js": "~0.11.4"
  },

**Comment by jcesarmobile** [comment]
Can you provide a sample app where the issue can be reproduced?

**Comment by jcesarmobile** [comment]
closing since there was no response
